include:
- project: gardenlinux/gardenlinux-package-build
  file:
  - pipeline/pipeline.yml

variables:
  # Define the source of this package
  SOURCE_NAME: 'aws-sdk-cpp'
  ORIG_TAR: 'aws-sdk-cpp_1.9.365.orig.tar.gz'
